name: '🛠️ CI'

on:
  workflow_dispatch:
    inputs:
      environments:
        description: 'Environments to deploy, ex: ["dev","qa", "prd"]'
        required: true
        default: '["dev","qa","prd"]'
        type: string
      tf_version:
        description: Terraform version to be used
        required: false
        default: latest
        type: string
      destroy: #Used string to force user to type 'true'
        description: Force Terraform to destroy the infrastructure
        type: string
        required: false
        default: 'false'
      working_directory:
        description: Terraform working directory
        type: string
        default: 'Terraform'

permissions:
  actions: write # This is required to read/write workflows, workflow runs and artifacts.
  contents: write # This is required for actions/checkout and to read/write repository contents, commits, branches, downloads, releases, and merges.
  id-token: write # This is required for requesting the JWT for OIDC.
  pull-requests: write # This is required to read/write pull requests and related comments, assignees, labels, milestones, and merges.

defaults:
  run:
    shell: bash

jobs:
  create-pull-request:
    runs-on: 'ubuntu-latest'
    name: Create Pull Request

    if: github.ref_name != 'main'

    outputs:
      pr_number: ${{ steps.create-pr.outputs.pr_number }}

    steps:
    - name: Checkout Working Directory
      uses: actions/checkout@v4   
            
    - name: Create pull request
      id: create-pr
      # uses: devops-infra/action-pull-request@v0.5.5
      # with:
      #   github_token: ${{ secrets.GITHUB_TOKEN }}
      #   target_branch: main
      #   allow_no_diff: true
      #   title: "[auto] Terraform plan (${{ github.action }} - ${{ github.run_id }})"
      #   body: "Please check the Terraform plan(s) bellow before approving this pull request."
      uses: diillson/auto-pull-request@v1.0.1
      with:
        destination_branch: "main"
        pr_title: "[auto] Terraform plan (${{ github.action }} - ${{ github.run_id }})"
        pr_body: |                                        
          "Please check the Terraform plan(s) bellow before approving this pull request."      

  code-analysis:
    runs-on: 'ubuntu-latest'
    name: Code Analysis
    needs: [create-pull-request]

    if: github.ref_name != 'main'

    steps:
    - name: Code analysis tests
      run: echo "Code analysis tests"

    - name: Pull request comment - 'If any step failed'
      if: failure()
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ needs.create-pull-request.outputs.pr_number }}
        body: |
          Code analysis failed, please check the logs ❌          

  #Call reusable workflow
  terraform-plan:
    name: Terraform plan
    needs: [code-analysis]

    if: github.ref_name != 'main'

    strategy:
      matrix: 
        environment: ${{ fromJson(inputs.environments) }}

    uses: ./.github/workflows/terraform-workflow.yml
    with:
      action: plan
      tf_version: ${{ inputs.tf_version }}
      destroy: ${{ inputs.destroy }}
      working_directory: ${{ inputs.working_directory }}
      backend_storage_account_name: ${{ vars.BACKEND_STORAGE_ACCOUNT_NAME }}
      backend_resouce_group_name: ${{ vars.BACKEND_RESOUCE_GROUP_NAME }}
      tf_plan_extra: -var-file="./global.tfvars" -var-file="./tfvars/${{ matrix.environment }}.tfvars"
      environment: ${{ matrix.environment }}

  comment-pull-request:
    runs-on: 'ubuntu-latest'
    name: Comment on Pull Request
    needs: [terraform-plan]

    if: github.ref_name != 'main'

    strategy:
      matrix: 
        environment: ${{ fromJson(inputs.environments) }}

    environment: ${{ matrix.environment }}

    steps:
    - name: Download the Terraform Plan Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.environment }}.plan
        path: ${{ inputs.working_directory }}

    - name: Pull request comment - 'Plan output'
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ needs.create-pull-request.outputs.pr_number }}
        body: |
          Terraform Plan: Completed 🌟
          Environment: ${{ matrix.environment }}
          Destroy: ${{ inputs.destroy }}

          ```
          ${{ inputs.working_directory }}/${{ matrix.environment }}.plan 

    - name: Pull request comment - 'If any step failed'
      if: failure()
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ needs.create-pull-request.outputs.pr_number }}
        body: |
          Terraform workflow failed for environment ${{ matrix.environment }}, please check the logs ❌               
          ```