name: '🛠️ CI'

on:
  workflow_dispatch:
    inputs:
      environments:
        description: 'Environments to deploy, ex: ["dev","qa", "prd"]'
        required: true
        default: '["dev","qa","prd"]'
        type: string
      tf_version:
        description: Terraform version to be used
        required: false
        default: latest
        type: string
      destroy: #Used string to force user to type 'true'
        description: Force Terraform to destroy the infrastructure
        type: string
        required: false
        default: 'false'

permissions:
  actions: write # This is required to read/write workflows, workflow runs and artifacts.
  contents: write # This is required for actions/checkout and to read/write repository contents, commits, branches, downloads, releases, and merges.
  id-token: write # This is required for requesting the JWT for OIDC.
  pull-requests: write # This is required to read/write pull requests and related comments, assignees, labels, milestones, and merges.

defaults:
  run:
    working-directory: "Terraform"
    shell: bash

jobs:
  open-pull-request:
    runs-on: 'ubuntu-latest'
    name: Open Pull Request

    if: github.ref_name != 'main'

    outputs:
      pr_number: ${{ steps.open-pr.outputs.pr_number }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4   
            
    - name: Open pull request
      id: open-pr
      uses: diillson/auto-pull-request@v1.0.1
      with:
        destination_branch: "main"
        pr_title: "[auto] Terraform plan (Workflow: ${{ github.workflow}} - Job ID: ${{ github.run_number }})"
        pr_body: |                                        
          Please check the Terraform plan(s) bellow before approving this pull request.

    - name: PR Number
      run: echo ${{steps.open-pr.outputs.pr_number}}
    
    - name: PR Created
      run: echo ${{steps.open-pr.outputs.pr_created}}

  code-analysis:
    runs-on: 'ubuntu-latest'
    name: Code Analysis
    needs: 
      - open-pull-request

    if: github.ref_name != 'main'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4   
    
    - name: Code analysis tests
      run: | 
        echo "Code analysis tests"
        echo "PR Number: ${{ needs.open-pull-request.outputs.pr_number }}"

    - name: Pull request comment - 'If any step failed'
      if: failure()
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ needs.open-pull-request.outputs.pr_number }}
        body: |
          Code analysis failed, please check the logs ❌          

  #Call reusable workflow
  terraform-plan:
    name: Terraform plan
    needs:
      - open-pull-request
      - code-analysis      

    if: github.ref_name != 'main'

    strategy:
      matrix: 
        environment: ${{ fromJson(inputs.environments) }}

    uses: ./.github/workflows/terraform-workflow.yml
    with:
      action: plan
      tf_version: ${{ inputs.tf_version }}
      destroy: ${{ inputs.destroy }}
      working_directory: "Terraform"
      tf_plan_extra: -var-file="./global.tfvars" -var-file="./tfvars/${{ matrix.environment }}.tfvars"
      environment: ${{ matrix.environment }}
      pr_number: ${{ needs.open-pull-request.outputs.pr_number }}

  comment-pull-request:
    runs-on: 'ubuntu-latest'
    name: Comment on Pull Request
    needs: 
      - open-pull-request
      - terraform-plan      

    if: github.ref_name != 'main'

    strategy:
      matrix: 
        environment: ${{ fromJson(inputs.environments) }}

    environment: ${{ matrix.environment }}

    steps:
    - name: Download the Terraform Plan Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.environment }}.txt
        path: ${{ inputs.working_directory }}

    - name: Create PR comment content
      working-directory: ${{ inputs.working_directory }}
      run: |
        ls -la  
        echo "PR_BODY<<EOF" >> $GITHUB_ENV
        Terraform Plan: Completed 🌟 >> $GITHUB_ENV
        Environment: ${{ matrix.environment }} >> $GITHUB_ENV
        Destroy: ${{ inputs.destroy }} >> $GITHUB_ENV
  
        ``` >> $GITHUB_ENV
        cat ./${{ matrix.environment }}.txt >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV    

    - name: Pull request comment - 'Plan output'
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ needs.open-pull-request.outputs.pr_number }}
        body: ${{ env.PR_BODY }}
        # body: |
        #   Terraform Plan: Completed 🌟
        #   Environment: ${{ matrix.environment }}
        #   Destroy: ${{ inputs.destroy }}

        #   ```
        #   ${{ inputs.working_directory }}/${{ matrix.environment }}.txt 

    - name: Pull request comment - 'If any step failed'
      if: failure()
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ needs.open-pull-request.outputs.pr_number }}
        body: |
          Terraform workflow failed for ${{ matrix.environment }} environment, please check the logs ❌               
          ```